### ISSUE TITLE
browser support 

### ISSUE THREAD

**Issue by sballesteros** [Tessmore/sbd#1]
Hello,

I would like to use this module in the browser (with browserify). 
Would you be ok to remove the dependencies to ```sanitize-html``` and ```sugar```?
I am happy to send a PR if that's something you are willing to consider.

IMO, cleaning all HTML from text should take place outside of this lib.
For instance if you are in a browser you would typically do:

```
var $p = document.getElementsByTagName('p')[0];
var sentences = tokenizer.sentences($p.textContent); //taking .textContent clean all the HTML within the p.
```

Dropping ```sugar``` will make the bundle smaller and won't result in much more code (once again, happy to send a PR for that).

Thanks!

Sebastien

**Comment by Tessmore** [comment]
Hey,

First off, this module is super simple, i.e. no training, just a few simple rules.  `sugar` is only used for splitting sentences into words, so I guess that dependency could be removed as it doesn't even properly seperates words. For example, `Hello<br>World!` is one word. 

This is why I use `sanitize-html`, because I didn't really need it to work on html. I agree that if html tags can be "ignored", but not removed is better.

I will gladly accept pull-requests!

**Comment by sballesteros** [comment]
Ok thanks!
I just sent a PR https://github.com/Tessmore/sbd/pull/2.

**Comment by Tessmore** [comment]
Looks good to me.

**Comment by sballesteros** [comment]
thanks, any chance you could publish that on npm?

**Comment by Tessmore** [comment]
Oh sorry, updated it for npm just now.
